name: Parser edsl

on:
  push:
    branches: [ main, geogreck-cw-wip ]
  pull_request:
    branches: [ main, geogreck-cw-wip ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          pip install pytest
          if [ -f requirements.txt ];
          then pip install -r requirements.txt; fi

      - name: Run tests
        run: |
          pytest
